[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "python-test-demo"
version = "0.1.0"
dependencies = ["fastapi", "pytest", "pytest-cov", "httpx", "requests"]

[tool.setuptools.packages.find]
where = ["."]
